service: questmaster

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  profile: default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
  environment:
    SLACK_CLIENT_ID: ${file(./config.json):SLACK.CLIENT_ID}
    SLACK_CLIENT_SECRET: ${file(./config.json):SLACK.CLIENT_SECRET}
    SLACK_BOT_TOKEN: ${file(./config.json):SLACK.BOT_TOKEN}

functions:
  events:
    handler: functions/index.handler
    events:
      - http:
          path: events
          method: post
